### ISSUE TITLE
Panel: Impossible to hide a panel when the window is right at the edge

### ISSUE THREAD

**Issue by SolarLune** [budgie-desktop/budgie-desktop#1050]
**Operating System**: Solus 2017.04.18.0 64-bit
**Budgie version**: budgie-desktop v10.3.1-400-gb70b63a

**The issue encountered**

When hiding a panel is turned on, it's not possible to show a panel if there's a window right at the edge. Only some programs do this - Peek is one that I have confirmed has this issue.

**Steps to reproduce the issue**
1. Set a panel to auto-hide at the bottom of the screen.
2. Open Peek and move it to the bottom edge.
2. Attempt to hover over the panel to show it - Peek will disallow the panel from unhiding. I'm not certain if this is intended behavior, though, given what Peek is designed for (making GIFs from the screen).

**Comment by ikeydoherty** [comment]
So this is because peek is set to always on top. If you leave a 1px gap then it still works fine. The alternative is that we make the panel always on top too, but that will very likely break stuff. Let's find out ..

**Comment by ikeydoherty** [comment]
So the window has:

`_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE`

The autohide behaviour works fine when the window border isn't in the way (because the border will always be above the panel itself), but the border itself is going to interfere. I'd suggest a 1px offset when using Peek, but honestly this isn't what I'd call abnormal behaviour. Peek isn't a "normal" application by any consideration. Not much we can do to fix it from the Budgie side.

**Comment by SolarLune** [comment]
OK, I thought that might be the case because of how Peek is designed to stay on top, so that makes sense. Thanks!
