### ISSUE TITLE
Skypeforlinux, qBittorrent, shutter .v.v. notification icon missing

### ISSUE THREAD

**Issue by thuandt** [budgie-desktop/budgie-desktop#1229]
**Operating System**: Ubuntu 17.10
**Budgie version**: Budgie 10.4

Before when I use Unity, all icon display as indicator in top menu, when switching to Budgie Desktop, I already enable "Status Indicator" but didn't see these icon.

Their process still running as background

**Comment by fossfreedom** [comment]
I'm not familiar with the first two in the list - but for shutter you need to add the Application Indicator applet to your panel since shutter in ubuntu has been patched to expect  App indicators.

Since this is a Ubuntu specific issue, I'll close this here - feel free to discuss on UB's issue tracker - https://github.com/UbuntuBudgie/budgie-desktop-environment
