### ISSUE TITLE
Login Menu does not mirror on external display

### ISSUE THREAD

**Issue by Immortalin** [budgie-desktop/budgie-desktop#1248]
**Operating System**: e.g. Ubuntu Budgie 17.10
**Budgie version**: i.e. Budgie 10.4

**The issue encountered**
Budgie login manager does not mirror on second display despite mirroring being enabled
 ...

**Steps to reproduce the issue**
1. Enable display mirroring
2. Reboot and attempt to login, login prompt stuck on primary monitor, display extends and does not mirror

 ...

**Comment by fossfreedom** [comment]
this isn't an issue with budgie desktop.  The login screen is provided by slick-greeter and is lightdm based.

If your issue persists with another lightdm greeter like lightdm-gtk-greeter then file a bug with lightdm on launchpad.net.

If you issue is fixed by lightdm-gtk-greeter then file a bug with slick-greeter - https://github.com/linuxmint/slick-greeter
