### ISSUE TITLE
Slick Greeter not falling back to default if image not accessible

### ISSUE THREAD

**Issue by theCalcaholic** [budgie-desktop/budgie-desktop#1335]
**Operating System**: Ubuntu Budgie 17.10
**Budgie version**: 10.04

*Description:* Slick Greeter will not display any background image at all if it can't read the users' desktop images. A better solution for this case would be to display the default background instead.

**How to reproduce:**
1. Create user with encrypted home directory (I assume that the home directories of all users must be encrypted).
2. Choose any image from the pictures folder as desktop background.
3. log out

**Expected Result:**
Since slick greeter can't read the image inside the encrypted home directory, it falls back to the default background configuration (in dconf: `x.dm.slick-greeter.background`).

**Actual result:**
Slick greeter shows a black background, horribly contrasting with the login mask and top panel.

**Comment by fossfreedom** [comment]
Under 17.10 lightdm is receiving background info via a ubuntu only patch to change the users background shown on a greeter such as slick.  It is nothing to-do with budgie per se.

As you would expect in an encrypted situation, no info is transferred from the users config to lightdm.

You need to define the background manually as per https://github.com/linuxmint/slick-greeter

Since this is not a budgie matter I will close this just to keep things tidy.  thanks.

**Comment by theCalcaholic** [comment]
Thank you. Defining the background manually did not work, neither in dconf nor by creating a config file (`/etc/lightdm/slick-greeter.conf`).
But I will refer to the slick-greeter repository for further issues.
I was under the wrong impression that you are maintaining your own fork of slick-greeter...
