### ISSUE TITLE
GtkPopover mapped in wrong position with bottom panel

### ISSUE THREAD

**Issue by fastrizwaan** [budgie-desktop/budgie-desktop#292]
The bug is very visible.

![output](https://cloud.githubusercontent.com/assets/1161682/12073208/55741a42-b137-11e5-9d93-e44152540599.gif)
##

**Comment by ikeydoherty** [comment]
It's not always. It's *only* on bottom panel.

**Comment by thauti** [comment]
Sorry for the duplicate.
I can try to search the problem, but I'm a little lost with the source code. 
What are the interesting files? (eg. Which manages the creation of menus from the menu, or handles the events)

**Comment by thauti** [comment]
Ok, after investigation, it seems that when BudgieMenu creates the BudgieMenuWindow it assigns the menu button (widget = new Gtk.ToggleButton();) as a parent to the BudgieMenuWindow ( popover = new BudgieMenuWindow(settings, widget);).
But the problem is that this button isn't always "totally ready" when the MenuWindow is created, so MenuWindow is created with a "unstable" parent.

Furthermore, GtkPopover position is set to GTK_POSITION_TOP by default. It seems like if we add set_position(GTK.PositionType.BOTTOM) in the constructor of BudgieMenuWindow, it reduces a little little bit the problem. It should not be excluded that the problem comes from Gtk Popover. https://github.com/GNOME/gtk/blob/master/gtk/gtkpopover.c

**Comment by Hacksaurus** [comment]
@thauti I know I shouldn't be commenting on this thread after a long time, but where is the file where you can change GTK_POSTITION_TOP TO GTK_POSITION_BOTTOM? 
Again sorry for commenting this after a long time...

**Comment by ikeydoherty** [comment]
That doesn't fix it @Hacksaurus

**Comment by Hacksaurus** [comment]
@ikeydoherty Oh... Is there a fix then?

**Comment by ikeydoherty** [comment]
Not for Budgie 10, no. It's intrinsic to GtkPopover itself, that is the widget that is broken, as a result of GTK's lazy-caching of size requests (at no point can you truly know both the position and size of a stock GTK widget and have it be any way accurate.)

**Comment by Hacksaurus** [comment]
Oh I see... So really I'm sort of stuck with it being at the top?... (For now?)

**Comment by ikeydoherty** [comment]
It does move down to the bottom once the initial animation completes.This only happens with the bottom panel fwiw. It's something we're addressing with Budgie 11

**Comment by Hacksaurus** [comment]
Ah I see... Ok thanks!
I really like the idea of this DE and DW!
Keep on the good work!

**Comment by ikeydoherty** [comment]
I actually figured out a workaround... ffd445717fb4e4d9509ee21d3dbdc76213f6b211
It's fixed.

**Comment by Hacksaurus** [comment]
@ikeydoherty Oh wow thanks! Will this workaround be implemented in the next Budgie update?

**Comment by ikeydoherty** [comment]
It's in 10.3 yea

**Comment by Hacksaurus** [comment]
Ah I C, Thanks again!

**Comment by zaughon** [comment]
Anyone else still having issues with this? 
Tested it in virtual box with freshly installed versions of both Ubuntu 16.04 and 17.04
budgie-desktop 10.3.1
It mainly happens with the volume control and the popup to turn off your pc etc. Occasionally still happens when you open the main Popover as well.

**Comment by fossfreedom** [comment]
@zaughon this is being tracked here https://github.com/budgie-desktop/budgie-desktop/issues/867

**Comment by zaughon** [comment]
Ah, thanks! @fossfreedom
