### ISSUE TITLE
Corebird execute issue.

### ISSUE THREAD

**Issue by Jarh57** [budgie-desktop/budgie-desktop#599]
Operating System: Solus 1.2.0.5
Budgie version: Budgie 10.2.7

Corebird execute works from Main Menu and terminal, but it doesn't work with Alt-F2.

This is the trace when i execute corebird from terminal if it helps:

**(corebird:14232): Gtk-WARNING **: Theme parsing error: style.css:14:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'**

**(corebird:14232): Gtk-WARNING **: Theme parsing error: style.css:231:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'**

**(corebird:14232): Gtk-WARNING **: Theme parsing error: style.css:237:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.**

**Comment by JannikHa** [comment]
Using **Arch Linux** with **Budgie 10.2.7** and successfully reproduced this problem.

I found the solution pretty quick though. The problem is, that **corebird's** .desktop file ( **/usr/share/applications/org.baedert.corebird.desktop** ) has **DBusActivatable** set to **true**. If you *comment that line out* or set **DBusActivatabe** to **false**, you can normally start it with **Terminal, Budgie Menu and Budgie-Run-Dialog**. Please give me a feedback if it worked for you. :)

**Comment by Jarh57** [comment]
Yeah!, I just changed DBus to false and it is working. I have tested with gedit and it works now too.

**Comment by JannikHa** [comment]
Awesome! Glad it's working for you :)

**Comment by JoshStrobl** [comment]
Issue has since been resolved (6779d38852781a7c9a9f0d0a565507e60a68eef7 in 10.2.9).
