### ISSUE TITLE
No easy way to bring back removed button for Raven

### ISSUE THREAD

**Issue by yarpus** [budgie-desktop/budgie-desktop#616]
**Operating System**:Solus 1.2.0.5 64-bit
**Budgie version**: 10.2.7

**The issue encountered**
After removal of Raven's applet button, there's no easy and accessible way to bring Raven panel back. There's CLI or shortcuts, but both are far from being user-friendly. There should be either an option in System Settings OR you should be able to access the applet from panel (right-click?).

**Steps to reproduce the issue**
1.     Remove Raven Configuration button from the only panel you have.
2.     Close Raven's configuration.
3.     There's no option to open it or modify panel using GUI anymore (either CLI or key shortcuts).

**Comment by ikeydoherty** [comment]
System Settings is GNOME Control Center, which we don't own and cannot extend.

What you're basically asking me to do, is to make a key that a user can put in a door, and still use, even if they break the key, or the door. Or remove the lock completely. What would you suggest as a *viable* alternative? Because I'm not putting right click in..

**Comment by yarpus** [comment]
Well, there's cli command to replace-panel. I'm not fully sure about its usage (it's fairly close to returning panel's configuration as default). Ikey?

**Comment by JoshStrobl** [comment]
This has since been resolved. 1) You can use keyboard shortcuts. 2) There is a reset option.
