### ISSUE TITLE
user feedback on menu usability

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#642]
budgie-desktop 10.2.7 - with Show Headers initially turned off - Ubuntu 16.10

user feedback - usability testing - would love to know your thoughts:

"
1. The budgie menu has two sections, the left panel with the groups and the right panel with the applications.  However, after the install, the right panel does not appear to make any sense.  Its not an alphabetical list of applications (like xubuntu’s whiskers menu) but is a recently used list??.  
2. However, once you launch an application, it it put to the top of the right menu – fine.  But, when you launch the second application, it is not put on the top of the right menu, but as the second item in the list and so on and so forth.  After launch a number of applications, the right menu loses its meaning.
3. Now, if you turn on Show Headers in the Raven setting, then the right panel has the applications with the group header.  However, again it does not make sense; as an example, there are 3 Accessories group listed."

**Comment by Snisser** [comment]
To your **1st point**. The Menu is sorted according to the applications usage. For me, for example, the menu is sorted like this:

Chromium > Settings > Files > Tweak Tool > Libreoffice Writer...

Because i use chromium the most, it's on the first place, i hope you understand what my point is :)

To your other points I can't really say anything to be honest, though the **group headers** thing is probably how it is, because Applications don't have just one category. So if application X has **Internet** and **Accessories** as categories, and application Y has **Internet** and **Office**, there probably will be two different **Internet** headers for them.

**Comment by ikeydoherty** [comment]
The behaviour is gonna be more like Brisk btw - if you're curious I'd advise checking that out and getting a feel for it.

**Comment by fossfreedom** [comment]
ta - when the next solus mate ISO is available will take a peek.
