### ISSUE TITLE
Enforce a modular architecture

### ISSUE THREAD

**Issue by nazar-pc** [budgie-desktop/budgie-desktop#693]
It was initially reported downstream, but appears to need upstream changes first: https://bugs.launchpad.net/budgie-remix/+bug/1617910

Currently major Budgie Desktop package budgie-core contains almost everything, while in fact different components in this package work wonderfully when used standalone (thanks for that!).

For instance, budgie-run-dialog, budgie-polkit-dialog, budgie-panel - all can be used independently. Also session config might be separated from budgie-core.

I'd like to see budgie-core separated into few smaller packages, where budgie-core will actually contain common stuff like translations (maybe renamed to budgie-data or budgie-common), while budgie-desktop package would depend on all necessary underlying packages.

This is much more modular approach, I think most other DEs I've seen have separate packages for panel, WM, session config and so on with an umbrella package on top that brings everything together.

It might also decrease download size on system upgrade, for instance, you do not need to download everything again if only fresh translations were uploaded.

**Comment by ikeydoherty** [comment]
So from your original report:

> I'm using budgie-run-dialog successfully, also budgie-panel works (even though is not well integrated with other desktop environments)

Budgie components just aren't meant to be used in other desktops, bluntly. When the time comes for Wayland, all that modularity won't mean squat as they'll all depend on a Budgie compositor.

The downstream argument about splitting is actually null & void. You can split up a source package however you want, irregardless of how it's split upstream. 

Back to the point at hand..

Translations are local to their point of origin. So we wouldn't have a single grand "budgie-translations" repo, and it has no benefit to Budgie itself, and causes convoluted development.

If we had a "libbudgie" or similar, and that had translation strings there, then they'd be local to the libbudgie. 

>  Also session config might be separated from budgie-core.

"budgie-core" is a concept that only exists in the Debuntu world. Note how we have a single repo here, "budgie-desktop", and nowhere, anywhere, is there a mention of "budgie-core".

As to the separation of the binaries themselves, I'm not all that opposed to it, so long as everything uses common shared libraries. The problem is though is that it makes maintenance of Budgie completely anal and then requires updates to multiple components :)

Here's what I'm thinking right now:

 - budgie-polkit-dialog
 - budgie-run-dialog
 - budgie-daemon

Those could be achieved now. With the rewrite we'd then want:

 - budgie-panel
 - budgie-wm

Note that Budgie Panel provides Raven as it is in-process. This is an architectural requirement currently as Raven interfaces with the panel internals to enable applet manipulation, etc.

This would then require sharing of the current components:

 - libsession
 - libbudgietheme

These could more than likely be part of a budgie-core package, that contains the shared top-level schemas common to all Budgie components.

It's a bit of a beastly move, but given our target of degnomification, probably beneficial too.
I'm approving this, but not on the grounds of some weird Debuntu concepts, but because modularity is unavoidable going forward, and is a Good Thing to do :)

**Comment by ikeydoherty** [comment]
OK this is now in progress and will result in a new GitHub org

**Comment by ikeydoherty** [comment]
You'll notice that the new organisation is in effect.

New repos are being created under: https://github.com/budgie-desktop

To facilitate an easier transition I'll be using the `budgie-core` name, so we don't dick over the Ubuntu Budgie Remix guys with the update.

**Comment by fossfreedom** [comment]
... deserves a smiley :)

**Comment by ikeydoherty** [comment]
There is an unavoidable gschema break with this shift. Currently `builtin-theme` and `dark-theme` live inside the *panel* gschema, which isn't acceptable in the new system. We cannot have everything depend on the panel for runtime cruft.

As such they'll be moved into a new toplevel schema within `budgie-core`, basically allowing some kind of crazy pick 'n mix system.

**Comment by Limdel** [comment]
best thing you could ever do.
budgie panel is awesome and I always wanted to use it. however, I have my own custom DE and installing whole new DE just for one application was not worth it for me. would be glad to use it after it will be separated.

**Comment by ikeydoherty** [comment]
Supporting your custom DE isn't the "best thing" I could ever do :P That's not the reason for doing it. Just a side effect

**Comment by Limdel** [comment]
I understand that this is just a side effect, but still, budgie was made with customization in mind and I think users shouldn't be forced to use whole DE without ability to uninstall and replace certain parts.
Can't appreciate something if I can't use it as I want to, even if it is as cool as budgie panel. :P

**Comment by ikeydoherty** [comment]
This doesn't need tracking its a thing we know
