### ISSUE TITLE
Issues with 10.2.8 on openSUSE Leap 42.1

### ISSUE THREAD

**Issue by geckolinux** [budgie-desktop/budgie-desktop#702]
Hi guys,

Issue #624 was resolved for openSUSE Tumbleweed thanks to Ikey's wizardry, but now there are problems on Leap 42.1. Mainly, the issues are two that got fixed on Tumbleweed:

- Panel items can not be moved. It seems that the up/down arrows are on a layer underneath the session buttons and are not clickable.
- Panel items can not be configured. Again I suspect this is because the configure button is on a layer underneath the Budgie session buttons. It is visible but not clickable.

This happens both with the internal Budgie theme enabled or disabled, and with a fresh dconf or with a custom dconf.

Thanks a lot for supporting Budgie on openSUSE!

**Comment by ikeydoherty** [comment]
What version of GTK is this?

**Comment by geckolinux** [comment]
GTK 3.16

**Comment by ikeydoherty** [comment]
Remember, I made this clear 10 months ago:

![screenshot from 2016-11-01 18-09-15](https://cloud.githubusercontent.com/assets/164489/19901231/541616fc-a05e-11e6-81da-300d38338512.png)

It's on https://build.opensuse.org/package/show/home:ikeydoherty:solus-project/budgie-desktop

I knew there would be issues going forward, and currently Budgie supports 3.16, 3.18, 3.20, and 3.22.
There's no way for us to provide support backwards for 3.16 while its all Vala/etc. We cannot do build conditionals because autotools ships the .c files.

Right now, unless someone has a stroke of genius, I seriously doubt there is anything we can do. We're trying to keep support limited within the scope of a normal LTS right now, and SLES falls well outside of those parameters.

**Comment by ikeydoherty** [comment]
So looking at the roadmap, y'all get 42.2 on November 16th, which will bring you GTK 3.18.
At that point we should drop 3.16 support from Budgie entirely, as I assume Gecko Linux will rebase on 42.2 ?

**Comment by geckolinux** [comment]
Ah OK, I just assumed from the .spec file that 3.16 was still supported. And yes, 42.2 will be out soon enough and I'll rebase GeckoLinux on that, so no point dedicating more time to working around this issue. I just really hope that you can continue to support Tumbleweed and 42.2, as Budgie seems to be a very popular option for GeckoLinux users. Thanks as always for your time Ikey.

**Comment by ikeydoherty** [comment]
Given the synchronicity with the openSUSE cycle I'm definitely not opposed to it. Currently the 42.1 stuff is giving me issues in OBS but those should go away now

**Comment by geckolinux** [comment]
Cool, I'll be looking forward to that. And as for the Tumbleweed fix, well done, it seems to be pretty much flawless with GTK 3.22.

**Comment by ikeydoherty** [comment]
There is one large major regression with 3.22, full screen windows are covered by the panel
