### ISSUE TITLE
Battery is Low, but shows Battery as charged..

### ISSUE THREAD

**Issue by Hacksaurus** [budgie-desktop/budgie-desktop#769]
I'm not sure if this is a GNOME of Budgie problem, but when I get the notification my battery is low, it shows that my battery is ok... I think this is either because there is no icon for low battery, you Budgie isn't programmed to do so...
![screenshot_2017-01-05_19-57-20](https://cloud.githubusercontent.com/assets/24832107/21708014/6277be90-d389-11e6-97dd-6e2068704d9d.png)

**Comment by fluffymadness** [comment]
I also had a weird problem with the battery indicator. But it last occurred to me, I think it was two weeks ago (haven't tested it since then, since my laptop is mainly docked atm)
It occured when the battery was low about 5 percent or so and you get the extra noisy notifications (a good thing btw)
I plugged in the charger the battery charged and the battery meter was showing the status in the gnome settings itself, but the battery icon in budgie didn't refresh with the actual charging status but was still red.
Had this bug I think 2-3 times.

**Comment by Vistaus** [comment]
@fluffymadness Same here. Have had that a couple of times as well.

**Comment by Hacksaurus** [comment]
Oh I see... 
*FURUSTRATION*
*Github Gods make the development speed of Budgie a lot faster!*

**Comment by ikeydoherty** [comment]
Eh. We have a roadmap. https://solus-project.com/2017/01/03/this-year-in-solus-2016-edition/

Budgie ain't it, yet.

**Comment by Hacksaurus** [comment]
Yeah... But I want it to go even faster!
I really want this project to be completely finished...
Just keep on fixing!

**Comment by cipricus** [comment]
I have this problem without any standby or other interruptions. The bad part is that the setting in `/etc/UPower/UPower.conf` that should put the system to sleep at a certain level, namely the line `PercentageAction`, is not followed.

The lines I have are:

`UsePercentageForPolicy=true
PercentageLow=15
PercentageCritical=10
PercentageAction=7
CriticalPowerAction=HybridSleep`

`systemctl hybrid-sleep` triggers the suspend state as it should.

The system starts signaling low (15) and critical levels (10) that I had set, but then **the displayed battery level remains blocked** at the one set at `PercentageCritical` line (10 in this case) and it is not reaching down to the one at which the system should sleep/suspend set by the PercentageAction line, which drains the battery down until shutdown.

**While the battery level display is blocked** at that level, t**he power settings window is missing the battery level completely**.  It looks like this:

![2017-03-21-171506_743x505_scrot](https://cloud.githubusercontent.com/assets/3447868/24157903/06886eba-0e5b-11e7-901c-2809a037b343.png)

instead of he normal way:

![2017-03-21-164440_741x533_scrot](https://cloud.githubusercontent.com/assets/3447868/24157933/20b7a602-0e5b-11e7-8951-4e09d53172b3.png)
