### ISSUE TITLE
HiDPI Issues

### ISSUE THREAD

**Issue by JLCCI** [budgie-desktop/budgie-desktop#830]
I have the newest Budgie and Solus and was wondering if there is any way to fix some of the HiDPI glitches and issues. There are a few but will focus on the more apparent ones.

1) Application menu text in applications like Atom or LibreOffice is too small to see on a 4K 27 inch screen. The fonts do not respect the Gnome Font scaling.

For Atom I found a package that scales everything within the window ('hidpi') but the menu text still stays tiny. I've read that installing libreoffice-gtk might help but it's not available so cannot test it. LibreOffice 5.3 removed font scaling.

![screenshot from 2017-03-23 11-21-19](https://cloud.githubusercontent.com/assets/18163728/24229110/5898c02c-0fbb-11e7-8c3d-f34ff777d310.png)
![screenshot from 2017-03-23 11-21-41](https://cloud.githubusercontent.com/assets/18163728/24229111/589b3af0-0fbb-11e7-92f1-01568012f8f9.png)

2) The title text in all windows is small again. I found that changing the resolution to a lower one and then again to the top one fixed it on my laptop (also 4K screen) but not on my computer (only some apps changed). Again gnome font scaling does not help.

![screenshot from 2017-03-23 11-23-14](https://cloud.githubusercontent.com/assets/18163728/24229115/5f580dc8-0fbb-11e7-976f-1839ac1251ca.png)

3) Not sure if this is a feature or a HiDPI glitch but the icons in the app list becomes blurry when selected. I don't think I have seen it in any online Solus photos.

![screenshot from 2017-03-23 11-24-40](https://cloud.githubusercontent.com/assets/18163728/24229119/63876146-0fbb-11e7-8d9c-bb178da128a3.png)
![screenshot from 2017-03-23 11-24-52](https://cloud.githubusercontent.com/assets/18163728/24229120/63c4822e-0fbb-11e7-928c-3a24ff6eb8e5.png)

With Budgie 11 coming I was not sure if I should report this or wait for new version but perhaps this also needs to be taken into account in the new version.

Many thanks for looking into this.

**Comment by CTXz** [comment]
Hey, as I've recently received a new laptop that features a HiDPI display, I'd like to contribute to this issue.

Most DPI related issues are not Solus or Budgie related but should rather be blamed on the application itself. DPI behavior highly depends on the GUI toolkit/library that is used by the application. 

As for window titles, I've managed to increase their size using the gnome-tweak-tool  under fonts > scaling factor. The only issue with that is that it affects much more than just the window titles. This is something that could be fixed by the budgie devs. As it seems like budgie window titles aren't registered as windows titles by the gnome tweak tool.

**Comment by JLCCI** [comment]
@CTXz Thanks for the comment. I am aware of the gnome-tweak-tool options but strangely there is much more HIDPI issues in Budgie than in gnome. The Font scaling does not seem to apply for most apps.

Guess we have to wait for Budgie 11 to see if some of those issues are resolved.

**Comment by gregflynn** [comment]
Hey @JLCCI, I use Budgie full time on a Dell XPS13 DE (Arch Linux) with the 1800p display with a 2x scaling factor, In addition to the tweak tool setting there's another scaling variable i have set:
```
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gdk/WindowScalingFactor': <2>}"
gsettings set org.gnome.desktop.interface scaling-factor 2
```

If you would like to see them used in a script to switch between 1x and 2x environments (for instance when using a laptop in clamshell mode with an external display, you can check out the scripts I posted here: https://www.reddit.com/r/archlinux/comments/5wokbx/dell_xps15_9560_kdeplasma5_scaling_issue_hidpi/debyr9m/

**Comment by JLCCI** [comment]
@gregflynn you're a genius, thank you! Small cursor, small menus, small window text was all solved with those two commands.

What would be the best way to have those two commands as default? The only way I can think of is to create an .sh script and add it to startup applications - perhaps there is some sort of config file where this could go to make it default.

**Comment by gregflynn** [comment]
@JLCCI You shouldn't need to run the commands more than once unless your screens change because these 2 commands write to the dconf registry (idk if it's taboo to call it a Registry but I did it)

So if all you do is run a Hidpi setup, run those commands and you're set unless a system update wipes those settings at some point. I set those keys on my laptop when I got it and haven't had to touch them since

**Comment by JLCCI** [comment]
@gregflynn Perfects, thanks a lot for your help, it is really appreciated.
