### ISSUE TITLE
Low battery notification

### ISSUE THREAD

**Issue by JLCCI** [budgie-desktop/budgie-desktop#835]
Every time the battery runs low on my laptop, instead of getting the notification with a single sound it makes the clicking sound several times in fast succession and the message keeps reappearing.

When I then plug in the cable the message pops up another 4 times and then everything is OK. Nothing major but probably easy to fix. Many thanks!

**Comment by JLCCI** [comment]
Also the battery indicator shows 2% (0:04) remaining regardless of how much it actually has. I have an XPS 15 laptop. Am I the only one with this issue?

**Comment by cipricus** [comment]
I think this is in fact related to a more severe issue: https://github.com/budgie-desktop/budgie-desktop/issues/746

Unless the panel is restarted or the machine plugged-in,  a few other things happen after the pop-ups end (and they end because probably the battery has gone under the critical level), all at level  specified by the line `PercentageCritical=` in `/etc/UPower/UPower.conf`. 

- the icon stays red

- the level displayed does **not** go under the one set as critical level - is stuck at that level

- the power manager window stops displaying the battery level (http://asksolus.com/wp-content/uploads/2017/03/2017-03-21-171506_743x505_scrot.png)

- the critical action set in the line `CriticalPowerAction` of the file `/etc/UPower/UPower.conf` is not followed and the battery drains out without any other notification until the computer shuts down by power failure

**Comment by ikeydoherty** [comment]
Most of what you said has nothing to do with Budgie itself btw - the fault is squarely on gnome-settings-daemon for most of it. Still, we'll need to find workarounds.

**Comment by cipricus** [comment]
@ikeydoherty - is the present issue related or even one and the same with https://github.com/budgie-desktop/budgie-desktop/issues/746? 

Setting `UsePercentageForPolicy=false` in `/etc/UPower/UPower.conf` changes nothing, as all the occurrences listed above happen at the time specified by the line `TimeCritical`.

**Comment by JLCCI** [comment]
Hm strange, I was using Gnome for a long time before switching to budgie and never had the battery problem.

Some issue are in fact a carry over - every time I lock or suspend the screen the default audio device gets switched on my PC. Never managed to fix it in Fedora and same happens in Solus.

In any case, happy to test some fixes if that helps. The battery indicator showing 2% all the time was not always there, the weird clicking sound and popup showing 10 times was always there though does not happens every single time.

**Comment by cipricus** [comment]
@JLCCI - From my experience, the red  icon, the repeated pop-up, the critically battery level displayed getting stuck and the fact that power manager window stops displaying the battery level (http://asksolus.com/wp-content/uploads/2017/03/2017-03-21-171506_743x505_scrot.png) are all related. **Also**,  the cause of these, whatever it may be, triggers (at lest in my case) the situation where computer is not suspended  (as critical action set in the line `CriticalPowerAction` of the file `/etc/UPower/UPower.conf`) when the battery gets very low.

**If not plugged to a power source: is your computer taking any action (like suspend) at a certain low level of the battery, or it just shuts down by power failure?**

That is: 

If you do 

`sudo gedit /etc/UPower/UPower.conf` 

and have the lines 
`UsePercentageForPolicy=true`
`PercentageAction=2`
 (that is the default, but can be changed on the condition that the values there are in descending order) and 
`CriticalPowerAction=HybridSleep`
(that requires having a swap partition I think)

then: is your machine suspended at that `PercentageAction` level? 

In my experience it is **not**, because:

- the battery level and report is stuck at the value set by `PercentageCritical` (my impression is that the display gets stuck at 2%, which is the default of `PercentageAction`, when the `PercentageCritical` is also at the default 3%, that is immediately close; if you set `PercentageCritical` higher, like 6 or 10%, than it will be stuck at **that** level).

- `PercentageCritical` has to be bigger than `PercentageAction`

Therefore, as the battery recorded level is stuck at `PercentageCritical`, the `PercentageAction` level is never recorded and action (like suspend) is never taken.

**Comment by JLCCI** [comment]
@cipricus don't even need to check it, just yesterday the laptop turned itself off when running low (after making the repeated sound couple of times).

In any case, it is not a huge problem. I am mainly reporting it to help with bug hunting, especially since Ikey is working on Budgie 11 and may look at some things more closely.

**Comment by cipricus** [comment]
@JLCCI  - I am trying to find more about this because I want to understand if all these occurrences that I have listed in my posts above **are related or not to a single cause** that stops my computer from suspending at critical battery (I much prefer sleep/suspend to shutdown).

From your report I assume you have the lines ` PercentageAction=2 ` and `CriticalPowerAction=PowerOff` in ` /etc/UPower/UPower.conf`.

I hope I'm not imposing, but I want to be sure: are you positive the shutdown is normal, not power failure?

**Comment by cipricus** [comment]
I also noticed that  if the  power manager window is open while the battery level display is stuck at the level `PercentageCritical` (I have even tested with 50%, and it gets stuck on that level too), that window freezes.

Also, I think that the battery plugin is crushing at this point, because in my case **if the panel is restarted (Ctrl-Alt-R) when the battery level display is stuck, the restarted panel has no battery button whatsoever.**

**Comment by JLCCI** [comment]
@cipricus Of course you are not imposing, I am happy to help if this will make Budgie better. 

I do have both of the lines you mentioned. I also CriticalPowerAction=HybridSleep . I can't do a test right now as I am downloading a large file but yesterday when the laptop was unplugged it powered off rather than hybernate.

I can't really say if this was a normal shutdown or power failure. Anything else I can do atm other that draining battery and seeing what happens?

**Comment by cipricus** [comment]
@JLCCI 

- Considering the "making Budgie better" part :) As you said in a post above, Ike Doherty is working on Budgie 11, which will switch to Qt. Reading his post on the reasons, I see he mentions problems between Budgie and the `gnome-settings-daemon`, which he also mentions in a post here as the culprit in reply to my list of problems that I had posted above. So, I suspect Budgie 11 will not be concerned by all these, and I am very much looking forward to this new development. The present Budgie is a huge progress compared to what I had seen about a year ago or more, and also the Linux that I like more at the present, but 11 should be even better. - So I fear (but I'm also glad) that my present problems here, although severe, are of little significance now to the project, which faces imminent and radical change.

- To differentiate between shutdown and power failure is easy. Shutdown (that happens when we press that panel option or with a command like  `systemctl poweroff` takes more time, has a few steps, at least 1-2 seconds, while the power failure is absolutely sudden, like when the battery were to be removed (that's what I see because of the problems reported above). You should check and be sure your computer is not suffering power failure, that is unsafe and must be avoided.

- In your case it is clear that your computer is not following the `CriticalPowerAction=HybridSleep` setting. There are also two lines that say: `# If HybridSleep isn't available, Hibernate will be used
# If Hibernate isn't available, PowerOff will be used`. So it may be that you don't have HybridSleep nor Hibernate available (I think you need a swap space for that, but see below about that) and that's why your computer is shutting down. Note that **suspend** as such (which any computer supports) is not available in the list of options.

- Considering swap space. I don't know why after startup my swap space is off in Solus. So, at that point I don't have HybridSleep nor Hibernate available. But after enabling it in Gparted (swapon), my computer is entering HybridSleep with the command `systemctl hybrid-sleep`. So, it would be very much able to use HybridSleep (just like I should be able to use ShutDown) if it weren't for that critical battery level problem that stops any action at that level on my system.

**Comment by JLCCI** [comment]
So I checked GParted and it seem the swap is on (judging by the fact that right click shows 'Swapoff'). However, when I press hibernate in the power button menu the computer turns itself off and when I press it again it logs in as if freshly booted (no stored session etc).

I am draining the batter to see how it shutdowns.

**Comment by cipricus** [comment]
@JLCCI - Hibernation is not supported on many computers (and it doesn't need Swap space in fact). I was talking about **Hybrid sleep** when I was mentioning swap space, and you should try `CriticalPowerAction=HybridSleep` in the file  `/etc/UPower/UPower.conf`,  whic should take place at ` PercentageAction=` level (that is what is not working in my case, and I was curious whether it worked on your system).

**Comment by JLCCI** [comment]
Ups sorry, though it is the same. Drained the battery and it looks like a power failure - nothing was restored after pressing power on button. 

systemctl hybrid-sleep did work as intended though.

**Comment by cipricus** [comment]
You can test by setting `CriticalPowerAction=HybridSleep` to about 5% under your present battery level, then restart computer and wait to see what happens. In my case battery report gets stuck at that level. (Oddly my battery button is completely gone now after latest updates).

**Comment by JLCCI** [comment]
FYI the reporting works without a problem now so I guess the issues is not the same as yours.

**Comment by cipricus** [comment]
I made a mistake: my battery report gets stuck at the level of `PercentageCritical` (not `PercentageAction`; the `PercentageLow` level is reported just fine, but at `PercentageCritical` it gets stuck so that it never gets to `PercentageAction`.

**Comment by JLCCI** [comment]
Budgie 11 is not far away so guess we will have to wait and see if all this is resolved. Will close for not as it's not something Ikey will have time to deal with.

**Comment by cipricus** [comment]
@JLCCI - Fully agree. 

I am adding the following because Ikey Doherty has mentioned the need for a workaround. - I have found one for my own needs. It involves the `uname` script posted [here](https://github.com/jerrinfrncs/batterynotif). (It doesn't fully work for me, but I can resolve it by using two separate versions o that script, as indicated [here](https://github.com/jerrinfrncs/batterynotif/issues/1#issuecomment-290920173).
