### ISSUE TITLE
cannot find anywhere to disable 'super' key in Ubuntu budgie 17.04 

### ISSUE THREAD

**Issue by 243750496** [budgie-desktop/budgie-desktop#874]
I disabled the key with gnome-tweak-tool but it still workingI mean when i press the 'super' button the pop up the launch Menu like the image attach below
I configured krita shotcut to use super installed of ctrl
So as u can imagine that each time while i press super the menu will pop up it's really annoying
But if you are in Ubuntu not budgie settings in unity tweak tool can change the super key to disabled
But in gnome-tweak-tool there seems no that key or function provide

**Comment by 243750496** [comment]
![6affdbf4-268d-11e7-8fd5-332579ee989d](https://cloud.githubusercontent.com/assets/6311930/25294567/52f6e694-2712-11e7-9f67-61f54b1d054e.jpg)

**Comment by haevalencia** [comment]
This site is only used to report bugs in the Budgie desktop environment. Your problem seems more tied to the particular distribution that is used, please look here: https://bugs.launchpad.net/ubuntubudgie

**Comment by ikeydoherty** [comment]
This has been opened 3 times now, twice as a highly broken pull request. Can someone please figure out what it is @243750496 is trying to attain, because at this rate I'm starting to believe there is trolling or bots involved (Especially given the bizarre username).

If someone from the Ubuntu team would like to liaison here, and I'll step down on the issue. If not then I'm going to have to block the user tomorrow, given the same activity within the last 24 hours.

The super key is reserved for the use of the menu within Budgie, explicitly. Unless there is a patch for this, it's not going to land in the Budgie 10.3 series, and won't be considered until Budgie 11.

**Comment by fossfreedom** [comment]
@243750496 it seems you are having a little trouble with your pull request.  Suggest just create a patch and let me have a look at it.  Pop into the community chatroom.  

Once we have figured out if the patch is good to submit, I'll talk you through how to-do a pull request.

I'll close this now and await to see your patch.

cheers.
