### ISSUE TITLE
Budgie on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by BobbyBabes** [budgie-desktop/budgie-desktop#894]
**Operating System**: openSUSE Tumbleweed
**Budgie version**: Budgie 10.3 update here : https://build.opensuse.org/package/show/home:devmotion:branches:X11:Solus/budgie-desktop

Over the last few days it was brought to my attention (in the linked subreddit) that someone built a Budgie Desktop update to v10.3 for openSUSE Tumbleweed.

I had good assistance at the openSUSE subreddit here : https://www.reddit.com/r/openSUSE/comments/67uqtk/is_the_opensuse_budgie_package_still_broken_on/

Today I was going to install openSUSE Tumbleweed with Budgie on top. But I postponed.
(To me Budgie is what GNOME should have been on the desktop. A desktop environment with a desktop UI.)

**I would first like to hear your opinion about Budgie's future on openSUSE.**
(I've read your comments in issues #264, #800, and #849.)

**Comment by ikeydoherty** [comment]
Not sure I follow. I released 10.3 as I said I would. I'm not sure why people are saying I abandoned openSUSE (perhaps sensationalism is just that popular)

I said quite some time ago that it wasn't appropriate for me to maintain the OBS repos for much longer. Other downstream distros had long since packaged Budgie up, and it was high time we went the inclusion route. Folks stepped forward, and the X11:Solus branch was born.

If the future of the X11:Solus project is now in doubt (seemingly so) I can push OBS updates out on my old repo if necessary, but I won't be doing this for Budgie 11.

**Comment by Mailaender** [comment]
https://build.opensuse.org/package/show/X11:Solus/budgie-desktop has been updated. Sorry for the delay. I force pushed @devmotion's update which he kept for himself.

**Comment by ikeydoherty** [comment]
Awesome stuff @Mailaender  - btw looks like its only building on Tumbleweed as its requiring `pkgconfig(libmutter-0)` - whereas older leap would use `pkgconfig(libmutter)` - might need a conditional of some sort in the spec

**Comment by Mailaender** [comment]
Oh, you kept support for both, but I guess meson is broken or too old on Leap:
```
[   77s] + /usr/bin/meson --prefix=/usr --buildtype=plain
[   78s] /usr/bin/meson <source directory> <build directory>
[   78s] If you omit either directory, the current directory is substituted.
[   78s] Run /usr/bin/meson --help for more information.
```

**Comment by ikeydoherty** [comment]
Oh damn. :(
