### ISSUE TITLE
How can I add my own tattoo into the budgie panel?

### ISSUE THREAD

**Issue by omerfeyyaz** [budgie-desktop/budgie-desktop#960]
Hello i want to add my own button to the budgie desktop panel and i want to open the whisker menu in xfce when I press the button.
NOTE: My distribution is Linux Mint Xfce 18 sarrah

**Comment by ikeydoherty** [comment]
Tattoo? Whisker Menu? XFCE? This issue is astoundingly confusing.

Budgie desktop has its own Applet API/ABI. Applets need to be written *for Budgie*.
There is no magical "launch random stuff not part of Budgie" thing. Also not Budgie is GTK3, and
Whisker is GTK2.

Also still don't know what you mean by tattoo.

**Comment by tristan957** [comment]
I say leave it open just for the laughs. Not entirely sure what Linux Mint and Xfce have to do with all this :D

**Comment by JoshStrobl** [comment]
Closing due to lack of response from reporter and general mixed signals as to what the issue or request even is.
